# This is a basic workflow to help you get started with Actions

name: CIMain

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
      
      - name: Use Node 
        uses: actions/setup-node@v1
        with:
          node-version: '16.10.0'
          #https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3
      # Runs a set of commands using the runners shell
      - name: Run the build
        run: | 
          npm i -g npm@8.3.0               
          cd src
          echo 'install angular'    
          npm i  @angular/cli@13
          # echo "install ws"
          #npm i -force
          #cd AutoBlocklyApp
          #npm i -force
          #cd ..
          # echo "copy "
          #cp -rn node_modules/  AutoBlocklyApp/          
          cp -rn node_modules/codemirror/  AutoBlocklyApp/codemirror          
          cp -rn node_modules/@types/codemirror/  AutoBlocklyApp/@types/codemirror
          ls -l AutoBlocklyApp/node_modules/codemirror
          # echo "find"
          find . -type d -name "codemirror" -print
          echo "build"
          npm run buildAng
          ls -l AutoBlocklyApp/dist/AutoBlocklyApp
          


