# This is a basic workflow to help you get started with Actions

name: CIMain

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
      
      - name: Use Node 
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      # Runs a set of commands using the runners shell
      - name: Run the build
        run: |
          echo 'start'
          cd src
          echo 'install angular'
          npm i @angular/cli@13.0.1  --force                 
          echo "install ws"
          npm i -ws --include-workspace-root --force                 
          ls -l node_modules/
          echo "copy "
          cp -r node_modules  AutoBlocklyApp/node_modules
          # ls -l AutoBlocklyApp/node_modules/*
          cd AutoBlocklyApp
          echo ' in angular force install '
          npm i --force   
          ls -l node_modules/              
          cd ..
          echo "build"
          npm run buildAng
          ls -l AutoBlocklyApp/dist/AutoBlocklyApp
          


