name: "tagged-release"

on:
  push:    
    tags:
      - "v*"
  
  workflow_dispatch:

jobs:
  buildAngular:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and npm run build
      run: |
        cd src
        npm i @angular/cli@13.0.1
        #npm i -g  @angular/cli@13.0.1
        npm i -ws --include-workspace-root                  
        cp -r node_modules  AutoBlocklyApp/node_modules        
        npm run buildGitHubPages
        cd ..
        rm -r docs/*
        cp -r src/AutoBlocklyApp/dist/AutoBlocklyApp/* docs/
        cp docs/index.html docs/404.html
        ls -l docs/
        

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: AutoBlocklyApp
        path: 'src/AutoBlocklyApp/dist/AutoBlocklyApp'
        retention-days: 1

    - name : autocommit
      run: |
        git config --global user.email "taggedrelease@ignatandrei.com"
        git config --global user.name "Tagged release"
        git add docs/*
        git commit -am "Auto commit from Github Action" --allow-empty
        git push origin main

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
    - name: Archive Release 
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'releaseBlocklyAutomation.zip'
        path: '${{github.workspace}}/src/AutoBlocklyApp/dist/AutoBlocklyApp'
        exclusions: '*.git* /*node_modules/* .editorconfig'       

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files:  |
            releaseBlocklyAutomation.zip
        # tag: v${{ env.GITHUB_SHA }}
        # tag_name: v${{ env.GITHUB_SHA }}
      

    - name: delete older-releases@v0
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        #repo: <owner>/<repoName> # defaults to current repo
        keep_latest: 2
        #delete_tag_pattern: beta # defaults to ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
